#
# =BEGIN MIT LICENSE
# 
# The MIT License (MIT)
#
# Copyright (c) 2014 The CrossBridge Team
# https://www.github.com/crossbridge-community
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# 
# =END MIT LICENSE
#

git: 
    depth: 1

language: objective-c

before_script:
    - brew update
    - brew install adobe-air-sdk
    - mkdir -p /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/11.1/
    - cp -f /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/15.0/playerglobal.swc /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/11.1/
    - "export AIR_HOME=/usr/local/opt/adobe-air-sdk/libexec"
    - mkdir -p ./crossbridge
    - mkdir -p ./mymount
    - wget -i install.txt
    - hdiutil attach ./CrossBridge_1.0.4.3.dmg -mountpoint ./mymount
    - rsync -l -r --exclude=.Trashes ./mymount/ ./crossbridge/
    - hdiutil detach /dev/disk1 -force
    - export _JAVA_OPTIONS="-Xms256m -Xmx2048m"

script:
    - make FLASCC=/Users/travis/build/crossbridge-community/crossbridge-swc-lua/crossbridge/sdk FLEX=/usr/local/opt/adobe-air-sdk/libexec